#include "pch.h"
#include "BgfxKeysMapping.h"

using namespace RED_LILIUM_NAMESPACE;

std::optional<Key> RED_LILIUM_NAMESPACE::convertBgfxKey(entry::Key::Enum key)
{
	switch (key)
	{
	case entry::Key::Esc:
		return Key::Esc;
	case entry::Key::Return:
		return Key::Return;
	case entry::Key::Tab:
		return Key::Tab;
	case entry::Key::Space:
		return Key::Space;
	case entry::Key::Backspace:
		return Key::Backspace;
	case entry::Key::Up:
		return Key::Up;
	case entry::Key::Down:
		return Key::Down;
	case entry::Key::Left:
		return Key::Left;
	case entry::Key::Right:
		return Key::Right;
	case entry::Key::Insert:
		return Key::Insert;
	case entry::Key::Delete:
		return Key::Delete;
	case entry::Key::Home:
		return Key::Home;
	case entry::Key::End:
		return Key::End;
	case entry::Key::PageUp:
		return Key::PageUp;
	case entry::Key::PageDown:
		return Key::PageDown;
	case entry::Key::Print:
		return Key::Print;
	case entry::Key::Plus:
		return Key::Plus;
	case entry::Key::Minus:
		return Key::Minus;
	case entry::Key::LeftBracket:
		return Key::LeftBracket;
	case entry::Key::RightBracket:
		return Key::RightBracket;
	case entry::Key::Semicolon:
		return Key::Semicolon;
	case entry::Key::Quote:
		return Key::Quote;
	case entry::Key::Comma:
		return Key::Comma;
	case entry::Key::Period:
		return Key::Period;
	case entry::Key::Slash:
		return Key::Slash;
	case entry::Key::Backslash:
		return Key::Backslash;
	case entry::Key::Tilde:
		return Key::Tilde;
	case entry::Key::F1:
		return Key::F1;
	case entry::Key::F2:
		return Key::F2;
	case entry::Key::F3:
		return Key::F3;
	case entry::Key::F4:
		return Key::F4;
	case entry::Key::F5:
		return Key::F5;
	case entry::Key::F6:
		return Key::F6;
	case entry::Key::F7:
		return Key::F7;
	case entry::Key::F8:
		return Key::F8;
	case entry::Key::F9:
		return Key::F9;
	case entry::Key::F10:
		return Key::F10;
	case entry::Key::F11:
		return Key::F11;
	case entry::Key::F12:
		return Key::F12;
	case entry::Key::NumPad0:
		return Key::NumPad0;
	case entry::Key::NumPad1:
		return Key::NumPad1;
	case entry::Key::NumPad2:
		return Key::NumPad2;
	case entry::Key::NumPad3:
		return Key::NumPad3;
	case entry::Key::NumPad4:
		return Key::NumPad4;
	case entry::Key::NumPad5:
		return Key::NumPad5;
	case entry::Key::NumPad6:
		return Key::NumPad6;
	case entry::Key::NumPad7:
		return Key::NumPad7;
	case entry::Key::NumPad8:
		return Key::NumPad8;
	case entry::Key::NumPad9:
		return Key::NumPad9;
	case entry::Key::Key0:
		return Key::Key0;
	case entry::Key::Key1:
		return Key::Key1;
	case entry::Key::Key2:
		return Key::Key2;
	case entry::Key::Key3:
		return Key::Key3;
	case entry::Key::Key4:
		return Key::Key4;
	case entry::Key::Key5:
		return Key::Key5;
	case entry::Key::Key6:
		return Key::Key6;
	case entry::Key::Key7:
		return Key::Key7;
	case entry::Key::Key8:
		return Key::Key8;
	case entry::Key::Key9:
		return Key::Key9;
	case entry::Key::KeyA:
		return Key::KeyA;
	case entry::Key::KeyB:
		return Key::KeyB;
	case entry::Key::KeyC:
		return Key::KeyC;
	case entry::Key::KeyD:
		return Key::KeyD;
	case entry::Key::KeyE:
		return Key::KeyE;
	case entry::Key::KeyF:
		return Key::KeyF;
	case entry::Key::KeyG:
		return Key::KeyG;
	case entry::Key::KeyH:
		return Key::KeyH;
	case entry::Key::KeyI:
		return Key::KeyI;
	case entry::Key::KeyJ:
		return Key::KeyJ;
	case entry::Key::KeyK:
		return Key::KeyK;
	case entry::Key::KeyL:
		return Key::KeyL;
	case entry::Key::KeyM:
		return Key::KeyM;
	case entry::Key::KeyN:
		return Key::KeyN;
	case entry::Key::KeyO:
		return Key::KeyO;
	case entry::Key::KeyP:
		return Key::KeyP;
	case entry::Key::KeyQ:
		return Key::KeyQ;
	case entry::Key::KeyR:
		return Key::KeyR;
	case entry::Key::KeyS:
		return Key::KeyS;
	case entry::Key::KeyT:
		return Key::KeyT;
	case entry::Key::KeyU:
		return Key::KeyU;
	case entry::Key::KeyV:
		return Key::KeyV;
	case entry::Key::KeyW:
		return Key::KeyW;
	case entry::Key::KeyX:
		return Key::KeyX;
	case entry::Key::KeyY:
		return Key::KeyY;
	case entry::Key::KeyZ:
		return Key::KeyZ;
	case entry::Key::GamepadA:
		return Key::GamepadA;
	case entry::Key::GamepadB:
		return Key::GamepadB;
	case entry::Key::GamepadX:
		return Key::GamepadX;
	case entry::Key::GamepadY:
		return Key::GamepadY;
	case entry::Key::GamepadThumbL:
		return Key::GamepadThumbL;
	case entry::Key::GamepadThumbR:
		return Key::GamepadThumbR;
	case entry::Key::GamepadShoulderL:
		return Key::GamepadShoulderL;
	case entry::Key::GamepadShoulderR:
		return Key::GamepadShoulderR;
	case entry::Key::GamepadUp:
		return Key::GamepadUp;
	case entry::Key::GamepadDown:
		return Key::GamepadDown;
	case entry::Key::GamepadLeft:
		return Key::GamepadLeft;
	case entry::Key::GamepadRight:
		return Key::GamepadRight;
	case entry::Key::GamepadBack:
		return Key::GamepadBack;
	case entry::Key::GamepadStart:
		return Key::GamepadStart;
	case entry::Key::GamepadGuide:
		return Key::GamepadGuide;
	}

	return std::nullopt;
}

std::optional<entry::Key::Enum> RED_LILIUM_NAMESPACE::convertBgfxKey(Key key)
{
	switch (key)
	{
	case Key::Esc:
		return entry::Key::Esc;
	case Key::Return:
		return entry::Key::Return;
	case Key::Tab:
		return entry::Key::Tab;
	case Key::Space:
		return entry::Key::Space;
	case Key::Backspace:
		return entry::Key::Backspace;
	case Key::Up:
		return entry::Key::Up;
	case Key::Down:
		return entry::Key::Down;
	case Key::Left:
		return entry::Key::Left;
	case Key::Right:
		return entry::Key::Right;
	case Key::Insert:
		return entry::Key::Insert;
	case Key::Delete:
		return entry::Key::Delete;
	case Key::Home:
		return entry::Key::Home;
	case Key::End:
		return entry::Key::End;
	case Key::PageUp:
		return entry::Key::PageUp;
	case Key::PageDown:
		return entry::Key::PageDown;
	case Key::Print:
		return entry::Key::Print;
	case Key::Plus:
		return entry::Key::Plus;
	case Key::Minus:
		return entry::Key::Minus;
	case Key::LeftBracket:
		return entry::Key::LeftBracket;
	case Key::RightBracket:
		return entry::Key::RightBracket;
	case Key::Semicolon:
		return entry::Key::Semicolon;
	case Key::Quote:
		return entry::Key::Quote;
	case Key::Comma:
		return entry::Key::Comma;
	case Key::Period:
		return entry::Key::Period;
	case Key::Slash:
		return entry::Key::Slash;
	case Key::Backslash:
		return entry::Key::Backslash;
	case Key::Tilde:
		return entry::Key::Tilde;
	case Key::F1:
		return entry::Key::F1;
	case Key::F2:
		return entry::Key::F2;
	case Key::F3:
		return entry::Key::F3;
	case Key::F4:
		return entry::Key::F4;
	case Key::F5:
		return entry::Key::F5;
	case Key::F6:
		return entry::Key::F6;
	case Key::F7:
		return entry::Key::F7;
	case Key::F8:
		return entry::Key::F8;
	case Key::F9:
		return entry::Key::F9;
	case Key::F10:
		return entry::Key::F10;
	case Key::F11:
		return entry::Key::F11;
	case Key::F12:
		return entry::Key::F12;
	case Key::NumPad0:
		return entry::Key::NumPad0;
	case Key::NumPad1:
		return entry::Key::NumPad1;
	case Key::NumPad2:
		return entry::Key::NumPad2;
	case Key::NumPad3:
		return entry::Key::NumPad3;
	case Key::NumPad4:
		return entry::Key::NumPad4;
	case Key::NumPad5:
		return entry::Key::NumPad5;
	case Key::NumPad6:
		return entry::Key::NumPad6;
	case Key::NumPad7:
		return entry::Key::NumPad7;
	case Key::NumPad8:
		return entry::Key::NumPad8;
	case Key::NumPad9:
		return entry::Key::NumPad9;
	case Key::Key0:
		return entry::Key::Key0;
	case Key::Key1:
		return entry::Key::Key1;
	case Key::Key2:
		return entry::Key::Key2;
	case Key::Key3:
		return entry::Key::Key3;
	case Key::Key4:
		return entry::Key::Key4;
	case Key::Key5:
		return entry::Key::Key5;
	case Key::Key6:
		return entry::Key::Key6;
	case Key::Key7:
		return entry::Key::Key7;
	case Key::Key8:
		return entry::Key::Key8;
	case Key::Key9:
		return entry::Key::Key9;
	case Key::KeyA:
		return entry::Key::KeyA;
	case Key::KeyB:
		return entry::Key::KeyB;
	case Key::KeyC:
		return entry::Key::KeyC;
	case Key::KeyD:
		return entry::Key::KeyD;
	case Key::KeyE:
		return entry::Key::KeyE;
	case Key::KeyF:
		return entry::Key::KeyF;
	case Key::KeyG:
		return entry::Key::KeyG;
	case Key::KeyH:
		return entry::Key::KeyH;
	case Key::KeyI:
		return entry::Key::KeyI;
	case Key::KeyJ:
		return entry::Key::KeyJ;
	case Key::KeyK:
		return entry::Key::KeyK;
	case Key::KeyL:
		return entry::Key::KeyL;
	case Key::KeyM:
		return entry::Key::KeyM;
	case Key::KeyN:
		return entry::Key::KeyN;
	case Key::KeyO:
		return entry::Key::KeyO;
	case Key::KeyP:
		return entry::Key::KeyP;
	case Key::KeyQ:
		return entry::Key::KeyQ;
	case Key::KeyR:
		return entry::Key::KeyR;
	case Key::KeyS:
		return entry::Key::KeyS;
	case Key::KeyT:
		return entry::Key::KeyT;
	case Key::KeyU:
		return entry::Key::KeyU;
	case Key::KeyV:
		return entry::Key::KeyV;
	case Key::KeyW:
		return entry::Key::KeyW;
	case Key::KeyX:
		return entry::Key::KeyX;
	case Key::KeyY:
		return entry::Key::KeyY;
	case Key::KeyZ:
		return entry::Key::KeyZ;
	case Key::GamepadA:
		return entry::Key::GamepadA;
	case Key::GamepadB:
		return entry::Key::GamepadB;
	case Key::GamepadX:
		return entry::Key::GamepadX;
	case Key::GamepadY:
		return entry::Key::GamepadY;
	case Key::GamepadThumbL:
		return entry::Key::GamepadThumbL;
	case Key::GamepadThumbR:
		return entry::Key::GamepadThumbR;
	case Key::GamepadShoulderL:
		return entry::Key::GamepadShoulderL;
	case Key::GamepadShoulderR:
		return entry::Key::GamepadShoulderR;
	case Key::GamepadUp:
		return entry::Key::GamepadUp;
	case Key::GamepadDown:
		return entry::Key::GamepadDown;
	case Key::GamepadLeft:
		return entry::Key::GamepadLeft;
	case Key::GamepadRight:
		return entry::Key::GamepadRight;
	case Key::GamepadBack:
		return entry::Key::GamepadBack;
	case Key::GamepadStart:
		return entry::Key::GamepadStart;
	case Key::GamepadGuide:
		return entry::Key::GamepadGuide;
	}

	return std::nullopt;
}
