version: '{build}'

clone_folder: c:\projects\RedLiliumEngine

image:
    - Visual Studio 2017

configuration:
    - Release
    - Debug

platform:
    - x64

environment:
  matrix:
    - arch: Win64
    
install:
    - git submodule update --init --recursive
    
before_build:
    - if exist build ( rd /s /q build )
    - mkdir build
    - cd build
    - cmake ../ -G "Visual Studio 15 2017 Win64"
    
build:
    project: '%APPVEYOR_BUILD_FOLDER%\build\RedLiliumEngine.sln'
    verbosity: normal
    parallel: true

test_script:
    - '%APPVEYOR_BUILD_FOLDER%\build\Bin\%CONFIGURATION%\Tests.exe'
    
only_commits:
  files:
    - CMakeLists.txt
    - appveyor.yml
    - Sources/
    - 3rdparty/
