version: '{build}'
branches:
  only:
    - master
    
clone_folder: c:\projects\RedLiliumEngine

image:
    - Visual Studio 2017

configuration:
    - Release
    - Debug

platform:
    - x64

environment:
  matrix:
    - arch: Win64
    
before_build:
    - ps: |
    if exist .build (
        rd /s /q .build
    )
    if exist .bin (
        rd /s /q .bin
    )
    mkdir .build
    cd .build
    cmake ../ -G "Visual Studio 15 2017 Win64"
    
build:
    project: c:\projects\RedLiliumEngine\build\RedLiliumEngine.sln
    verbosity: normal
    parallel: true

only_commits:
  files:
    - CMakeLists.txt
    - appveyor.yml
    - src/
    - 3rdparty/
