#pragma once

#if _DEBUG
#define RED_LILIUM_POINTER_COUNTERS 1
#define RED_LILIUM_USE_ASSERTS 1
#define RED_LILIUM_USE_TELEMETRY 1
#define RED_LILIUM_USE_GPU_MEMORY_PROFILER 1
#define RED_LILIUM_USE_MEMORY_PROFILER 1
#else
#define RED_LILIUM_POINTER_COUNTERS 0
#define RED_LILIUM_USE_ASSERTS 0
#define RED_LILIUM_USE_TELEMETRY 0
#define RED_LILIUM_USE_GPU_MEMORY_PROFILER 0
#define RED_LILIUM_USE_MEMORY_PROFILER 0
#endif // _DEBUG

#define RED_LILIUM_SINGLE_THREAD_MODE 1

#define RED_LILIUM_GUARD(LEVEL)
#define RED_LILIUM_SCOPE(LEVEL, NAME)
